### Prepare & Process Dataset
- Identify data type
- Call back what process need in the next step regarding to the 10 question test case
- Prepare datset for: <br>
    1. Analysis
    2. Create Model and Evaluation
    3. Predict next month

In [1]:
# import library needed
import pandas as pd
import numpy as np
import re

In [2]:
# load dataset
df_raw = pd.read_csv("telco_customer_churn.csv")

# identify data type
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [3]:
# display top 5 dataframe
df_raw.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# transform column suppose to be numeric
print('''
TotalCharges suppose to be numeric value, float
''')

df_raw['TotalCharges'] = pd.to_numeric(df_raw['TotalCharges'], errors='coerce')
df_raw.info()

TotalCharges suppose to be numeric value, float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [5]:
# fill NaN value in TotalCharges with mean
df_raw['TotalCharges'].fillna(df_raw['TotalCharges'].mean(), inplace=True)
print("Sum if ane null value for each columns: ")
df_raw.isnull().sum()

Sum if ane null value for each columns:

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
# save df_raw
df_raw.to_csv("df_raw_prepared.csv", index=False)

### Data type of dataset was ready for further analysis

### Call Back:

#### ***9: Buatlah machine learning model untuk memprediksi pelanggan yang akan churn dibulan berikutnya dan tunjukan hasil evaluasi model tersebut***

#### ***10: Jelaskan Fitur apa saja yang paling berpengaruh pada model anda dan berapa banyak pelanggan yang akan churn di bulan berikutnya***


#### Breakdown and Plan

> Breakdown:
- Untuk membuat model machine learning dan melakukan evaluasi performa, dibutuhkan dataset untuk training dan testing.
- Untuk melakukan prediksi bulan berikutnya, apabila tidak disediakan data test, kita perlu membuat hold out dataset atau unseen dataset.
    
> Plan:
- Data train dan testing kita sebut sebagai data ML development, porsinya sekitar 80-90% dari raw data
- Sedangkan unseen dataset (data bulan berikutnya) sekitar 10-20% dari raw data, dengan komposisi label yang seimbang (misalnya 15 churn, 15 no churn) sehingga kita akan dapat mengukur bagaimana performa model memprediksi data baru diluar machine learning development.

### Unseen Dataset

In [7]:
# Identify number of labels

df_procc = df_raw.copy()
df_procc = df_procc.sort_values(by=['Churn'])
print("Count Labels")
df_procc['Churn'].value_counts()

Count Labels

No     5174
Yes    1869
Name: Churn, dtype: int64

In [8]:
df_procc.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
4334,3969-GYXEL,Female,0,No,No,11,Yes,No,Fiber optic,Yes,...,No,No,No,No,Month-to-month,No,Electronic check,76.40,838.70,No
4333,5325-UWTWJ,Male,0,Yes,No,31,Yes,Yes,Fiber optic,Yes,...,No,Yes,No,No,Month-to-month,Yes,Credit card (automatic),90.55,2929.75,No
4332,4194-FJARJ,Female,0,Yes,Yes,54,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),60.00,3273.95,No
4331,5743-KHMNA,Male,0,No,No,71,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),25.55,1898.10,No

In [9]:
df_procc.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5441,3512-IZIKN,Female,0,Yes,No,70,Yes,Yes,DSL,Yes,...,Yes,Yes,No,No,Two year,No,Credit card (automatic),65.30,4759.75,Yes
1161,5868-CZJDR,Male,0,No,Yes,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,31.35,31.35,Yes
1159,4086-YQSNZ,Female,1,Yes,No,3,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.40,224.05,Yes
1163,0135-NMXAP,Female,0,No,No,12,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),89.75,1052.40,Yes
2974,1481-ZUWZA,Male,0,No,No,28,Yes,Yes,Fiber optic,Yes,...,No,No,No,Yes,Month-to-month,Yes,Credit card (automatic),94.50,2659.40,Yes

In [10]:
# take 15 rows randomly for each labels
churn_yes = df_procc[df_procc['Churn']=="Yes"]
churn_no = df_procc[df_procc['Churn']=="No"]

unseen_yes = churn_yes.sample(n=15)
unseen_no = churn_no.sample(n=15)

unseen_dataset = pd.concat([unseen_yes,unseen_no], ignore_index=True)
print(unseen_dataset.shape)
unseen_dataset

(30, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,4847-QNOKA,Female,0,No,No,1,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),44.90,44.90,Yes
1,5103-MHMHY,Female,0,No,Yes,1,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,No,Mailed check,45.95,45.95,Yes
2,1455-ESIQH,Male,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,89.10,89.10,Yes
3,8784-CGILN,Female,0,No,No,18,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),99.85,1776.95,Yes
4,9821-POOTN,Male,0,Yes,No,35,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.20,2576.20,Yes
5,2321-OMBXY,Female,0,Yes,Yes,38,Yes,No,DSL,Yes,...,No,Yes,Yes,Yes,One year,No,Credit card (automatic),80.30,3058.65,Yes
6,2984-MIIZL,Male,0,No,No,4,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.80,321.90,Yes
7,3254-YRILK,Male,1,No,No,19,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,88.20,1775.80,Yes
8,6646-QVXLR,Male,1,Yes,No,62,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Electronic check,103.75,6383.35,Yes
9,1704-NRWYE,Female,1,No,No,9,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.85,751.65,Yes
10,0137-OCGAB,Female,0,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,80.20,80.20,Yes
11,4844-JJWUY,Female,1,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,86.00,86.00,Yes
12,0207-MDKNV,Female,0,No,No,15,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Month-to-month,No,Electronic check,105.10,1582.75,Yes
13,2433-KMEAS,Male,0,No,No,22,Yes,Yes,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,54.45,1127.35,Yes
14,2626-URJFX,Male,0,Yes,Yes,4,Yes,Yes,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,50.90,225.60,Yes
15,5061-PBXFW,Female,0,Yes,Yes,32,Yes,No,DSL,Yes,...,No,Yes,No,No,Month-to-month,No,Bank transfer (automatic),61.40,1864.65,No
16,5076-YVXCM,Male,0,No,No,51,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,No,Bank transfer (automatic),83.40,4149.45,No
17,2761-XECQW,Male,1,Yes,No,8,No,No phone service,DSL,No,...,Yes,No,No,Yes,Month-to-month,Yes,Mailed check,43.35,371.40,No
18,3824-RHKVR,Female,0,No,No,17,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card (automatic),19.70,340.35,No
19,8221-HVAYI,Male,0,Yes,Yes,35,Yes,Yes,DSL,Yes,...,Yes,Yes,No,No,Two year,Yes,Credit card (automatic),69.15,2490.15,No
20,8316-BBQAY,Female,0,No,No,65,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),59.95,3921.10,No
21,9086-YJYXS,Male,0,Yes,Yes,34,Yes,Yes,DSL,No,...,Yes,No,Yes,Yes,One year,No,Bank transfer (automatic),77.20,2753.80,No
22,4801-KFYKL,Male,0,No,Yes,8,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Bank transfer (automatic),19.45,159.20,No
23,7542-CYDDM,Male,0,No,No,18,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.05,358.50,No
24,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,Yes,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No
25,6480-YAGIY,Male,0,No,No,45,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,No,Credit card (automatic),112.20,5031.85,No
26,8605-ITULD,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,19.55,19.55,No
27,3982-DQLUS,Male,1,Yes,Yes,65,Yes,Yes,Fiber optic,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,85.75,5688.45,No
28,5914-XRFQB,Male,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),115.80,8424.90,No
29,6892-BOGQE,Female,0,Yes,No,71,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),20.90,1493.20,No

In [11]:
# save unseen dataset as a next month dataset
unseen_dataset.to_csv("unseen_dataset.csv", index=False)

### Data train and test (Machine learning development)

In [12]:
# define list of id unseen dataset (with condition ID must be unique in the raw dataset)
list_id_unseen = unseen_dataset['customerID'].tolist()

# select raw dataset if customerID not in list_id_unseen
df_development = df_raw[~df_raw['customerID'].isin(list_id_unseen)]
print(df_development.shape)
print("Number of row dataset compare with raw dataset about: ", round(len(df_development)/len(df_raw), 5)*100, "%")

df_development.head()

(7013, 21)
Number of row dataset compare with raw dataset about:  99.574 %

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [13]:
# save data train and data test for further anlisys and development
df_development.to_csv("df_development.csv", index=False)

### Result & Reveal

1. Number of rows of raw dataset about 7043, we saved the dataframe in csv named "df_raw_prepared.csv"
2. Number of rows of unseeen dataset about 30, we take a few rows just because we need more data training and testing **(regarding to the imbalance class of churn label, will not beneficial if under represented label too much reduced)**. Slicing 30 rows with 50:50 proportion class is enough to simulate as a next month dataset. We saved the dataframe in csv named "unseen_dataset.csv"
3. Number of rows of data train+data test about 7013, we will split this dataframe into 75-80% as training set and the rest as testing/model evaluation set. We saved the dataframe in csv named "df_development.csv"